import { alpha } from './alpha.mjs';

const CUSTOM = {
  black: '#000000',
  white: '#FFFFFF',
  debugRed: '#FFB4AB',
  debugGreen: '#A8DAB5',
  debugYellow: '#F5B873',
  debugCyan: '#88D8E3',
  debugPurple: '#D8B9FF',
  diffGreen: '#A8DAB5',
  diffRed: '#FFB4AB',
  bracketCyan: '#88D8E3',
  bracketPurple: '#D0BCFF',
  bracketYellow: '#F5B873',
  bracketGreen: '#A8DAB5',
  bracketPink: '#FFB4AB',
};

export const COLOR_MAP = {
  // ── Focus ──
  focusBorder: 'primary',
  'sash.hoverBorder': 'primary',

  // ── Foreground / Text ──
  foreground: 'onSurface',
  disabledForeground: 'outline',
  descriptionForeground: 'onSurfaceVariant',
  errorForeground: 'error',
  'icon.foreground': 'onSurface',
  'window.activeBorder': 'surfaceVariant',
  'window.inactiveBorder': 'surfaceContainer',
  'widget.border': 'surfaceVariant',
  'widget.shadow': () => alpha(CUSTOM.black, 0.5),
  'selection.background': p => alpha(p.primaryContainer, 0.5),

  // ── Contrast ──
  contrastBorder: '#00000000',
  contrastActiveBorder: '#00000000',

  // ── Text Layout ──
  'textBlockQuote.background': 'surfaceContainer',
  'textBlockQuote.border': 'primary',
  'textCodeBlock.background': 'surfaceContainer',
  'textLink.activeForeground': 'secondary',
  'textLink.foreground': 'secondary',
  'textPreformat.foreground': 'onSurface',
  'textPreformat.background': 'surfaceContainer',
  'textPreformat.border': 'surfaceVariant',
  'textSeparator.foreground': 'outline',

  // ── Toolbar ──
  'toolbar.hoverBackground': 'surfaceVariant',
  'toolbar.hoverOutline': 'primary',
  'toolbar.activeBackground': 'surfaceVariant',

  // ── Editor Action List ──
  'editorActionList.background': 'surfaceContainer',
  'editorActionList.foreground': 'onSurface',
  'editorActionList.focusForeground': 'onPrimaryContainer',
  'editorActionList.focusBackground': 'surfaceVariant',

  // ── Button ──
  'button.background': 'primary',
  'button.foreground': 'onPrimary',
  'button.border': 'primary',
  'button.separator': 'surfaceVariant',
  'button.hoverBackground': 'onPrimaryContainer',
  'button.secondaryForeground': 'onSurface',
  'button.secondaryBackground': 'surfaceVariant',
  'button.secondaryHoverBackground': 'onSurfaceVariant',
  'button.secondaryBorder': 'surfaceVariant',

  // ── Checkbox ──
  'checkbox.background': 'surfaceVariant',
  'checkbox.foreground': 'primary',
  'checkbox.border': 'surfaceVariant',
  'checkbox.selectBackground': p => alpha(p.primary, 0.25),
  'checkbox.selectBorder': 'primary',
  'checkbox.disabled.background': 'surfaceContainer',
  'checkbox.disabled.foreground': 'outline',

  // ── Radio ──
  'radio.activeForeground': 'primary',
  'radio.activeBackground': p => alpha(p.primary, 0.25),
  'radio.activeBorder': 'primary',
  'radio.inactiveForeground': 'outline',
  'radio.inactiveBackground': 'surfaceVariant',
  'radio.inactiveBorder': 'surfaceVariant',
  'radio.inactiveHoverBackground': 'onSurfaceVariant',

  // ── Dropdown ──
  'dropdown.background': 'surfaceContainer',
  'dropdown.listBackground': 'surfaceContainer',
  'dropdown.border': 'surfaceVariant',
  'dropdown.foreground': 'onSurface',

  // ── Input ──
  'input.background': 'surfaceDim',
  'input.border': 'surfaceVariant',
  'input.foreground': 'onSurface',
  'input.placeholderForeground': 'outline',
  'inputOption.activeBackground': p => alpha(p.primary, 0.25),
  'inputOption.activeBorder': 'primary',
  'inputOption.activeForeground': 'onPrimaryContainer',
  'inputOption.hoverBackground': 'surfaceVariant',
  'inputValidation.errorBackground': p => alpha(p.error, 0.25),
  'inputValidation.errorForeground': 'error',
  'inputValidation.errorBorder': 'error',
  'inputValidation.infoBackground': p => alpha(p.secondary, 0.25),
  'inputValidation.infoForeground': 'secondary',
  'inputValidation.infoBorder': 'secondary',
  'inputValidation.warningBackground': () => alpha(CUSTOM.debugYellow, 0.25),
  'inputValidation.warningForeground': () => CUSTOM.debugYellow,
  'inputValidation.warningBorder': () => CUSTOM.debugYellow,

  // ── Scrollbar ──
  'scrollbar.background': 'surfaceContainer',
  'scrollbar.shadow': () => alpha(CUSTOM.black, 0.5),
  'scrollbarSlider.background': p => alpha(p.onSurfaceVariant, 0.5),
  'scrollbarSlider.hoverBackground': p => alpha(p.primary, 0.38),
  'scrollbarSlider.activeBackground': p => alpha(p.primary, 0.5),

  // ── Badge / Progress ──
  'badge.foreground': 'onPrimary',
  'badge.background': 'primary',
  'progressBar.background': 'primary',

  // ── List / Tree ──
  'list.activeSelectionBackground': 'primaryContainer',
  'list.activeSelectionForeground': 'onPrimaryContainer',
  'list.activeSelectionIconForeground': 'onPrimaryContainer',
  'list.dropBackground': p => alpha(p.primary, 0.25),
  'list.focusBackground': 'surfaceVariant',
  'list.focusForeground': 'onPrimaryContainer',
  'list.focusHighlightForeground': 'primary',
  'list.focusOutline': 'primary',
  'list.focusAndSelectionOutline': 'primary',
  'list.highlightForeground': 'primary',
  'list.hoverBackground': p => alpha(p.surfaceVariant, 0.3),
  'list.hoverForeground': 'onPrimaryContainer',
  'list.inactiveSelectionBackground': p => alpha(p.surfaceVariant, 0.4),
  'list.inactiveSelectionForeground': 'onSurface',
  'list.inactiveSelectionIconForeground': 'onSurface',
  'list.inactiveFocusBackground': 'surfaceContainer',
  'list.inactiveFocusOutline': 'surfaceVariant',
  'list.invalidItemForeground': 'error',
  'list.errorForeground': 'error',
  'list.warningForeground': () => CUSTOM.debugYellow,
  'list.deemphasizedForeground': 'outline',
  'list.dropBetweenBackground': p => alpha(p.primary, 0.25),
  'listFilterWidget.background': 'surfaceContainer',
  'listFilterWidget.outline': 'primary',
  'listFilterWidget.noMatchesOutline': 'error',
  'listFilterWidget.shadow': () => alpha(CUSTOM.black, 0.25),
  'list.filterMatchBackground': p => alpha(p.primary, 0.25),
  'list.filterMatchBorder': 'primary',
  'tree.indentGuidesStroke': 'surfaceVariant',
  'tree.inactiveIndentGuidesStroke': 'surfaceContainer',
  'tree.tableColumnsBorder': 'surfaceVariant',
  'tree.tableOddRowsBackground': p => alpha(CUSTOM.black, 0.12),

  // ── Activity Bar ──
  'activityBar.background': 'surface',
  'activityBar.dropBorder': 'primary',
  'activityBar.foreground': 'onSurface',
  'activityBar.inactiveForeground': 'onSurfaceVariant',
  'activityBar.border': 'surface',
  'activityBar.activeBorder': 'primary',
  'activityBar.activeBackground': p => alpha(p.primary, 0.12),
  'activityBar.activeFocusBorder': 'primary',
  'activityBarBadge.background': 'primary',
  'activityBarBadge.foreground': 'onPrimary',
  'activityBarTop.foreground': 'onSurface',
  'activityBarTop.activeBorder': 'primary',
  'activityBarTop.inactiveForeground': 'onSurfaceVariant',
  'activityBarTop.dropBorder': 'primary',
  'activityBarTop.background': 'surface',
  'activityBarTop.activeBackground': p => alpha(p.primary, 0.12),
  'activityWarningBadge.foreground': 'onPrimary',
  'activityWarningBadge.background': () => CUSTOM.debugYellow,
  'activityErrorBadge.foreground': () => CUSTOM.white,
  'activityErrorBadge.background': 'error',
  'profileBadge.background': 'primary',
  'profileBadge.foreground': 'onPrimary',
  'profiles.sashBorder': 'surfaceVariant',

  // ── Action Bar ──
  'actionBar.toggledBackground': p => alpha(p.primary, 0.25),

  // ── Agent Session ──
  'agentSessionReadIndicator.foreground': 'primary',
  'agentSessionSelectedBadge.border': 'primary',
  'agentSessionSelectedUnfocusedBadge.border': 'outline',
  'agentStatusIndicator.background': 'primary',
  'aiCustomizationManagement.sashBorder': 'surfaceVariant',

  // ── Side Bar ──
  'sideBar.background': 'surface',
  'sideBar.foreground': 'onSurfaceVariant',
  'sideBar.border': 'surface',
  'sideBar.dropBackground': p => alpha(p.primary, 0.25),
  'sideBarTitle.foreground': 'onSurface',
  'sideBarTitle.background': 'surface',
  'sideBarTitle.border': 'surface',
  'sideBarSectionHeader.background': 'surfaceContainer',
  'sideBarSectionHeader.foreground': 'onSurface',
  'sideBarSectionHeader.border': 'surfaceVariant',
  'sideBarActivityBarTop.border': 'surfaceVariant',
  'sideBarStickyScroll.background': 'surfaceContainer',
  'sideBarStickyScroll.border': 'surfaceVariant',
  'sideBarStickyScroll.shadow': () => alpha(CUSTOM.black, 0.25),

  // ── Minimap ──
  'minimap.background': 'surface',
  'minimap.findMatchHighlight': 'primary',
  'minimap.selectionHighlight': 'surfaceVariant',
  'minimap.errorHighlight': 'error',
  'minimap.warningHighlight': () => CUSTOM.debugYellow,
  'minimap.infoHighlight': 'secondary',
  'minimap.chatEditHighlight': () => CUSTOM.bracketCyan,
  'minimap.selectionOccurrenceHighlight': p => alpha(p.primary, 0.5),
  'minimap.foregroundOpacity': p => alpha(p.onSurface, 0.38),
  'minimapSlider.background': p => alpha(p.onSurfaceVariant, 0.5),
  'minimapSlider.hoverBackground': p => alpha(p.primary, 0.38),
  'minimapSlider.activeBackground': p => alpha(p.primary, 0.5),
  'minimapGutter.addedBackground': () => CUSTOM.diffGreen,
  'minimapGutter.modifiedBackground': 'secondary',
  'minimapGutter.deletedBackground': 'error',
  'editorMinimap.inlineChatInserted': () => alpha(CUSTOM.diffGreen, 0.25),

  // ── Editor Group ──
  'editorGroup.border': 'surfaceVariant',
  'editorGroup.dropBackground': p => alpha(p.primary, 0.25),
  'editorGroup.emptyBackground': 'surface',
  'editorGroup.focusedEmptyBorder': 'primary',
  'editorGroup.dropIntoPromptForeground': () => CUSTOM.white,
  'editorGroup.dropIntoPromptBackground': 'primary',
  'editorGroup.dropIntoPromptBorder': 'primary',
  'editorGroupHeader.noTabsBackground': 'surface',
  'editorGroupHeader.tabsBackground': 'surface',
  'editorGroupHeader.tabsBorder': 'surfaceVariant',
  'editorGroupHeader.border': 'surfaceVariant',

  // ── Tabs ──
  'tab.activeBackground': 'surfaceContainer',
  'tab.unfocusedActiveBackground': 'surfaceContainer',
  'tab.activeForeground': 'primary',
  'tab.border': 'surface',
  'tab.activeBorder': 'primary',
  'tab.selectedBorderTop': 'primary',
  'tab.selectedBackground': 'surfaceDim',
  'tab.selectedForeground': 'onPrimaryContainer',
  'tab.dragAndDropBorder': 'primary',
  'tab.unfocusedActiveBorder': 'surfaceVariant',
  'tab.activeBorderTop': 'primary',
  'tab.unfocusedActiveBorderTop': 'surfaceVariant',
  'tab.lastPinnedBorder': 'surfaceVariant',
  'tab.inactiveBackground': 'surface',
  'tab.unfocusedInactiveBackground': 'surface',
  'tab.inactiveForeground': 'outline',
  'tab.unfocusedActiveForeground': 'onSurface',
  'tab.unfocusedInactiveForeground': 'outline',
  'tab.hoverBackground': 'surfaceVariant',
  'tab.unfocusedHoverBackground': 'surfaceContainer',
  'tab.hoverForeground': 'onPrimaryContainer',
  'tab.unfocusedHoverForeground': 'onSurface',
  'tab.hoverBorder': 'primary',
  'tab.unfocusedHoverBorder': 'surfaceVariant',
  'tab.activeModifiedBorder': 'primary',
  'tab.inactiveModifiedBorder': 'secondary',
  'tab.unfocusedActiveModifiedBorder': p => alpha(p.primary, 0.5),
  'tab.unfocusedInactiveModifiedBorder': p => alpha(p.secondary, 0.5),

  // ── Editor Pane / SideBySide ──
  'editorPane.background': 'surfaceDim',
  'sideBySideEditor.horizontalBorder': 'surfaceVariant',
  'sideBySideEditor.verticalBorder': 'surfaceVariant',

  // ── Editor Core ──
  'editor.background': 'surface',
  'editor.foreground': 'onSurface',
  'editorLineNumber.foreground': 'outline',
  'editorLineNumber.activeForeground': 'onSurface',
  'editorLineNumber.dimmedForeground': 'surfaceVariant',
  'editorCursor.background': 'surface',
  'editorCursor.foreground': 'primary',
  'editorMultiCursor.primary.foreground': 'onPrimaryContainer',
  'editorMultiCursor.primary.background': p => alpha(p.primary, 0.25),
  'editorMultiCursor.secondary.foreground': 'onSurface',
  'editorMultiCursor.secondary.background': p => alpha(p.secondary, 0.25),
  'editor.placeholder.foreground': 'outline',
  'editor.compositionBorder': 'primary',

  // ── Editor Selection ──
  'editor.selectionBackground': p => alpha(p.primaryContainer, 0.5),
  'editor.selectionForeground': 'onPrimaryContainer',
  'editor.inactiveSelectionBackground': p => alpha(p.primaryContainer, 0.25),
  'editor.selectionHighlightBackground': p => alpha(p.primary, 0.12),
  'editor.selectionHighlightBorder': p => alpha(p.primary, 0.25),

  // ── Editor Word Highlight ──
  'editor.wordHighlightBackground': p => alpha(p.secondary, 0.12),
  'editor.wordHighlightBorder': p => alpha(p.secondary, 0.25),
  'editor.wordHighlightStrongBackground': () => alpha(CUSTOM.debugYellow, 0.12),
  'editor.wordHighlightStrongBorder': () => alpha(CUSTOM.debugYellow, 0.25),
  'editor.wordHighlightTextBackground': () => alpha(CUSTOM.diffGreen, 0.12),
  'editor.wordHighlightTextBorder': () => alpha(CUSTOM.diffGreen, 0.25),

  // ── Editor Find ──
  'editor.findMatchBackground': p => alpha(p.primary, 0.38),
  'editor.findMatchForeground': () => CUSTOM.white,
  'editor.findMatchHighlightBackground': p => alpha(p.secondary, 0.25),
  'editor.findMatchHighlightForeground': 'onPrimaryContainer',
  'editor.findRangeHighlightBackground': () => alpha(CUSTOM.debugYellow, 0.12),
  'editor.findMatchBorder': 'primary',
  'editor.findMatchHighlightBorder': 'secondary',
  'editor.findRangeHighlightBorder': () => CUSTOM.debugYellow,
  'search.resultsInfoForeground': 'onSurface',
  'searchEditor.findMatchBackground': p => alpha(p.primary, 0.38),
  'searchEditor.findMatchBorder': 'primary',
  'searchEditor.textInputBorder': 'surfaceVariant',

  // ── Editor Hover / Highlight ──
  'editor.hoverHighlightBackground': p => alpha(p.primary, 0.12),
  'editor.lineHighlightBackground': p => alpha(p.surfaceVariant, 0.25),
  'editor.inactiveLineHighlightBackground': p => alpha(p.surfaceVariant, 0.12),
  'editor.lineHighlightBorder': 'surfaceVariant',
  'editorUnicodeHighlight.border': 'error',
  'editorUnicodeHighlight.background': p => alpha(p.error, 0.25),
  'editorLink.activeForeground': 'secondary',
  'editor.rangeHighlightBackground': p => alpha(p.primary, 0.12),
  'editor.rangeHighlightBorder': p => alpha(p.primary, 0.25),
  'editor.symbolHighlightBackground': p => alpha(p.primary, 0.12),
  'editor.symbolHighlightBorder': p => alpha(p.primary, 0.25),

  // ── Editor Whitespace / Indent ──
  'editorWhitespace.foreground': 'surfaceVariant',
  'editorIndentGuide.background1': 'surfaceVariant',
  'editorIndentGuide.background2': 'surfaceVariant',
  'editorIndentGuide.background3': 'surfaceVariant',
  'editorIndentGuide.background4': 'surfaceVariant',
  'editorIndentGuide.background5': 'surfaceVariant',
  'editorIndentGuide.background6': 'surfaceVariant',
  'editorIndentGuide.activeBackground1': 'onSurfaceVariant',
  'editorIndentGuide.activeBackground2': 'onSurfaceVariant',
  'editorIndentGuide.activeBackground3': 'onSurfaceVariant',
  'editorIndentGuide.activeBackground4': 'onSurfaceVariant',
  'editorIndentGuide.activeBackground5': 'onSurfaceVariant',
  'editorIndentGuide.activeBackground6': 'onSurfaceVariant',
  'editorIndentGuide.background': 'surfaceVariant',
  'editorIndentGuide.activeBackground': 'onSurfaceVariant',

  // ── Editor Ruler ──
  'editorRuler.foreground': 'surfaceVariant',

  // ── Editor Inlay Hints ──
  'editorInlayHint.background': p => alpha(p.primary, 0.12),
  'editorInlayHint.foreground': 'primary',
  'editorInlayHint.typeForeground': 'secondary',
  'editorInlayHint.typeBackground': p => alpha(p.secondary, 0.12),
  'editorInlayHint.parameterForeground': () => CUSTOM.debugYellow,
  'editorInlayHint.parameterBackground': () => alpha(CUSTOM.debugYellow, 0.12),

  // ── Editor Linked Editing ──
  'editor.linkedEditingBackground': p => alpha(p.primary, 0.12),

  // ── Editor CodeLens ──
  'editorCodeLens.foreground': 'outline',

  // ── Editor LightBulb ──
  'editorLightBulb.foreground': () => CUSTOM.debugYellow,
  'editorLightBulbAutoFix.foreground': () => CUSTOM.diffGreen,
  'editorLightBulbAi.foreground': 'primary',

  // ── Editor Bracket Match ──
  'editorBracketMatch.background': p => alpha(p.primaryContainer, 0.5),
  'editorBracketMatch.border': 'primary',
  'editorBracketMatch.foreground': 'onPrimaryContainer',
  'editorBracketHighlight.foreground1': () => CUSTOM.bracketPurple,
  'editorBracketHighlight.foreground2': () => CUSTOM.debugYellow,
  'editorBracketHighlight.foreground3': () => CUSTOM.diffGreen,
  'editorBracketHighlight.foreground4': 'secondary',
  'editorBracketHighlight.foreground5': () => CUSTOM.bracketCyan,
  'editorBracketHighlight.foreground6': 'error',
  'editorBracketHighlight.unexpectedBracket.foreground': 'error',
  'editorBracketPairGuide.activeBackground1': p => alpha(p.primary, 0.5),
  'editorBracketPairGuide.activeBackground2': () => alpha(CUSTOM.debugYellow, 0.5),
  'editorBracketPairGuide.activeBackground3': () => alpha(CUSTOM.diffGreen, 0.5),
  'editorBracketPairGuide.activeBackground4': p => alpha(p.secondary, 0.5),
  'editorBracketPairGuide.activeBackground5': () => alpha(CUSTOM.bracketCyan, 0.5),
  'editorBracketPairGuide.activeBackground6': p => alpha(p.error, 0.5),
  'editorBracketPairGuide.background1': p => alpha(p.surfaceVariant, 0.5),
  'editorBracketPairGuide.background2': p => alpha(p.surfaceVariant, 0.5),
  'editorBracketPairGuide.background3': p => alpha(p.surfaceVariant, 0.5),
  'editorBracketPairGuide.background4': p => alpha(p.surfaceVariant, 0.5),
  'editorBracketPairGuide.background5': p => alpha(p.surfaceVariant, 0.5),
  'editorBracketPairGuide.background6': p => alpha(p.surfaceVariant, 0.5),

  // ── Editor Fold ──
  'editor.foldBackground': 'surfaceVariant',
  'editor.foldPlaceholderForeground': 'outline',

  // ── Editor Overview Ruler ──
  'editorOverviewRuler.background': 'surface',
  'editorOverviewRuler.border': 'surfaceVariant',
  'editorOverviewRuler.findMatchForeground': p => alpha(p.primary, 0.5),
  'editorOverviewRuler.rangeHighlightForeground': () => alpha(CUSTOM.debugYellow, 0.5),
  'editorOverviewRuler.selectionHighlightForeground': p => alpha(p.primary, 0.5),
  'editorOverviewRuler.wordHighlightForeground': p => alpha(p.secondary, 0.5),
  'editorOverviewRuler.wordHighlightStrongForeground': () => alpha(CUSTOM.debugYellow, 0.5),
  'editorOverviewRuler.wordHighlightTextForeground': () => alpha(CUSTOM.diffGreen, 0.5),
  'editorOverviewRuler.modifiedForeground': p => alpha(p.secondary, 0.5),
  'editorOverviewRuler.addedForeground': () => alpha(CUSTOM.diffGreen, 0.5),
  'editorOverviewRuler.deletedForeground': p => alpha(p.error, 0.5),
  'editorOverviewRuler.errorForeground': p => alpha(p.error, 0.5),
  'editorOverviewRuler.warningForeground': () => alpha(CUSTOM.debugYellow, 0.5),
  'editorOverviewRuler.infoForeground': p => alpha(p.secondary, 0.5),
  'editorOverviewRuler.bracketMatchForeground': p => alpha(p.primary, 0.5),
  'editorOverviewRuler.inlineChatInserted': () => alpha(CUSTOM.diffGreen, 0.5),
  'editorOverviewRuler.inlineChatRemoved': p => alpha(p.error, 0.5),
  'editorOverviewRuler.commentDraftForeground': 'primary',
  'editorOverviewRuler.commentForeground': 'outline',
  'editorOverviewRuler.commentUnresolvedForeground': 'primary',
  'editorOverviewRuler.commonContentForeground': p => alpha(p.primary, 0.5),
  'editorOverviewRuler.currentContentForeground': () => alpha(CUSTOM.diffGreen, 0.5),
  'editorOverviewRuler.incomingContentForeground': p => alpha(p.secondary, 0.5),

  // ── Editor Diagnostics ──
  'editorError.foreground': 'error',
  'editorError.border': 'error',
  'editorError.background': p => alpha(p.error, 0.12),
  'editorWarning.foreground': () => CUSTOM.debugYellow,
  'editorWarning.border': () => CUSTOM.debugYellow,
  'editorWarning.background': () => alpha(CUSTOM.debugYellow, 0.12),
  'editorInfo.foreground': 'secondary',
  'editorInfo.border': 'secondary',
  'editorInfo.background': p => alpha(p.secondary, 0.12),
  'editorHint.foreground': () => CUSTOM.bracketCyan,
  'editorHint.border': () => CUSTOM.bracketCyan,
  'problemsErrorIcon.foreground': 'error',
  'problemsWarningIcon.foreground': () => CUSTOM.debugYellow,
  'problemsInfoIcon.foreground': 'secondary',
  'editorUnnecessaryCode.border': 'onSurfaceVariant',
  'editorUnnecessaryCode.opacity': p => alpha(p.onSurfaceVariant, 0.5),

  // ── Editor Gutter ──
  'editorGutter.background': 'surface',
  'editorGutter.modifiedBackground': 'secondary',
  'editorGutter.modifiedSecondaryBackground': p => alpha(p.secondary, 0.5),
  'editorGutter.addedBackground': () => CUSTOM.diffGreen,
  'editorGutter.addedSecondaryBackground': () => alpha(CUSTOM.diffGreen, 0.5),
  'editorGutter.deletedBackground': 'error',
  'editorGutter.deletedSecondaryBackground': p => alpha(p.error, 0.5),
  'editorGutter.commentDraftForeground': 'primary',
  'editorGutter.commentDraftBackground': p => alpha(p.primary, 0.12),
  'editorGutter.commentDraftGlyphForeground': 'primary',
  'editorGutter.commentGlyphForeground': 'outline',
  'editorGutter.commentRangeForeground': 'outline',
  'editorGutter.commentUnresolvedGlyphForeground': 'primary',
  'editorGutter.foldingControlForeground': 'onSurface',
  'editorGutter.itemBackground': p => alpha(p.primary, 0.12),
  'editorGutter.itemGlyphForeground': 'primary',

  // ── Editor Widget ──
  'editorWidget.background': 'surfaceContainer',
  'editorWidget.border': 'surfaceVariant',
  'editorWidget.resizeBorder': 'primary',
  'editorSuggestWidget.background': 'surfaceContainer',
  'editorSuggestWidget.border': 'surfaceVariant',
  'editorSuggestWidget.foreground': 'onSurface',
  'editorSuggestWidget.selectedBackground': 'surfaceVariant',
  'editorSuggestWidget.highlightForeground': 'primary',
  'editorSuggestWidgetStatus.foreground': 'outline',
  'editorHoverWidget.background': 'surfaceContainer',
  'editorHoverWidget.border': 'surfaceVariant',
  'editorHoverWidget.foreground': 'onSurface',
  'editorHoverWidget.statusBarBackground': 'surfaceVariant',
  'editorHoverWidget.highlightForeground': 'primary',
  'editorWidget.foreground': 'onSurface',
  'editorSuggestWidget.focusHighlightForeground': 'primary',
  'editorSuggestWidget.selectedForeground': 'onPrimaryContainer',
  'editorSuggestWidget.selectedIconForeground': 'onPrimaryContainer',

  // ── Sticky Scroll ──
  'editorStickyScroll.background': 'surfaceContainer',
  'editorStickyScroll.border': 'surfaceVariant',
  'editorStickyScroll.shadow': () => alpha(CUSTOM.black, 0.25),
  'editorStickyScrollHover.background': 'surfaceVariant',
  'editorStickyScrollGutter.background': 'surfaceContainer',

  // ── Ghost Text ──
  'editorGhostText.background': p => alpha(p.surfaceVariant, 0.5),
  'editorGhostText.border': 'surfaceVariant',
  'editorGhostText.foreground': 'outline',

  // ── Diff Editor ──
  'diffEditor.border': 'surfaceVariant',
  'diffEditor.diagonalFill': 'surfaceVariant',
  'diffEditor.insertedLineBackground': () => alpha(CUSTOM.diffGreen, 0.12),
  'diffEditor.insertedTextBackground': () => alpha(CUSTOM.diffGreen, 0.25),
  'diffEditor.insertedTextBorder': () => CUSTOM.diffGreen,
  'diffEditor.move.border': () => CUSTOM.diffGreen,
  'diffEditor.moveActive.border': () => CUSTOM.diffGreen,
  'diffEditor.removedLineBackground': p => alpha(p.error, 0.12),
  'diffEditor.removedTextBackground': p => alpha(p.error, 0.25),
  'diffEditor.removedTextBorder': 'error',
  'diffEditor.unchangedCodeBackground': 'surfaceDim',
  'diffEditor.unchangedRegionBackground': 'surfaceContainer',
  'diffEditor.unchangedRegionForeground': 'onSurfaceVariant',
  'diffEditor.unchangedRegionShadow': () => alpha(CUSTOM.black, 0.25),
  'diffEditorGutter.insertedLineBackground': () => alpha(CUSTOM.diffGreen, 0.5),
  'diffEditorGutter.removedLineBackground': p => alpha(p.error, 0.5),
  'diffEditorOverview.insertedForeground': () => alpha(CUSTOM.diffGreen, 0.5),
  'diffEditorOverview.removedForeground': p => alpha(p.error, 0.5),
  'multiDiffEditor.background': 'surface',
  'multiDiffEditor.border': 'surfaceVariant',
  'multiDiffEditor.headerBackground': 'surfaceContainer',

  // ── Editor Comments Widget ──
  'editorCommentsWidget.rangeActiveBackground': p => alpha(p.primary, 0.25),
  'editorCommentsWidget.rangeBackground': p => alpha(p.primary, 0.12),
  'editorCommentsWidget.replyInputBackground': 'surfaceDim',
  'editorCommentsWidget.resolvedBorder': 'outline',
  'editorCommentsWidget.unresolvedBorder': 'primary',

  // ── Editor Marker Navigation ──
  'editorMarkerNavigation.background': 'surfaceContainer',
  'editorMarkerNavigationError.background': p => alpha(p.error, 0.12),
  'editorMarkerNavigationError.headerBackground': p => alpha(p.error, 0.25),
  'editorMarkerNavigationInfo.background': p => alpha(p.secondary, 0.12),
  'editorMarkerNavigationInfo.headerBackground': p => alpha(p.secondary, 0.25),
  'editorMarkerNavigationWarning.background': () => alpha(CUSTOM.debugYellow, 0.12),
  'editorMarkerNavigationWarning.headerBackground': () => alpha(CUSTOM.debugYellow, 0.25),

  // ── Peek View ──
  'peekView.border': 'primary',
  'peekViewEditor.background': 'surfaceDim',
  'peekViewEditor.matchHighlightBackground': p => alpha(p.primary, 0.25),
  'peekViewEditorGutter.background': 'surface',
  'peekViewResult.background': 'surfaceContainer',
  'peekViewResult.fileForeground': 'onSurface',
  'peekViewResult.lineForeground': 'onSurfaceVariant',
  'peekViewResult.matchHighlightBackground': p => alpha(p.primary, 0.25),
  'peekViewResult.selectionBackground': 'surfaceVariant',
  'peekViewResult.selectionForeground': 'onPrimaryContainer',
  'peekViewTitle.background': 'surface',
  'peekViewTitleLabel.foreground': 'onPrimaryContainer',
  'peekViewTitleDescription.foreground': 'onSurfaceVariant',
  'peekViewEditor.matchHighlightBorder': 'primary',
  'peekViewEditorStickyScroll.background': 'surfaceContainer',
  'peekViewEditorStickyScrollGutter.background': 'surfaceContainer',

  // ── Panel ──
  'panel.background': 'surface',
  'panel.border': 'surfaceVariant',
  'panel.dropBorder': 'primary',
  'panelTitle.activeBorder': 'primary',
  'panelTitle.activeForeground': 'onPrimaryContainer',
  'panelTitle.inactiveForeground': 'onSurfaceVariant',
  'panelInput.border': 'surfaceVariant',
  'panelInput.background': 'surfaceDim',
  'panelInput.foreground': 'onSurface',
  'panelStickyScroll.background': 'surfaceContainer',
  'panelStickyScroll.border': 'surfaceVariant',
  'panelStickyScroll.shadow': () => alpha(CUSTOM.black, 0.25),
  'outputView.background': 'surface',
  'outputViewStickyScroll.background': 'surfaceContainer',
  'panelSection.border': 'surfaceVariant',
  'panelSection.dropBackground': p => alpha(p.primary, 0.25),
  'panelSectionHeader.background': 'surfaceContainer',
  'panelSectionHeader.border': 'surfaceVariant',
  'panelSectionHeader.foreground': 'onSurface',
  'panelTitle.border': 'primary',
  'panelTitleBadge.background': 'primary',
  'panelTitleBadge.foreground': 'onPrimary',

  // ── Status Bar ──
  'statusBar.background': 'primaryContainer',
  'statusBar.foreground': 'onPrimaryContainer',
  'statusBar.border': 'surface',
  'statusBar.debuggingBackground': () => '#93000A',
  'statusBar.debuggingForeground': () => '#FFDAD6',
  'statusBar.focusBorder': 'primary',
  'statusBar.noFolderBackground': 'surface',
  'statusBarItem.compactHoverBackground': 'surfaceVariant',
  'statusBarItem.errorBackground': 'error',
  'statusBarItem.errorForeground': () => CUSTOM.white,
  'statusBarItem.focusBorder': 'primary',
  'statusBarItem.hoverBackground': 'surfaceVariant',
  'statusBarItem.prominentBackground': 'primary',
  'statusBarItem.prominentForeground': () => CUSTOM.white,
  'statusBarItem.remoteBackground': 'secondary',
  'statusBarItem.remoteForeground': () => CUSTOM.white,
  'statusBar.debuggingBorder': 'surface',
  'statusBar.noFolderBorder': 'surface',
  'statusBar.noFolderForeground': 'onSurface',
  'statusBarItem.activeBackground': p => alpha(p.primary, 0.25),
  'statusBarItem.errorHoverBackground': p => alpha(p.error, 0.25),
  'statusBarItem.errorHoverForeground': 'error',
  'statusBarItem.hoverForeground': 'onPrimaryContainer',
  'statusBarItem.offlineBackground': 'surfaceVariant',
  'statusBarItem.offlineForeground': 'onSurfaceVariant',
  'statusBarItem.offlineHoverBackground': 'onSurfaceVariant',
  'statusBarItem.offlineHoverForeground': 'onSurface',
  'statusBarItem.prominentHoverBackground': 'onPrimaryContainer',
  'statusBarItem.prominentHoverForeground': 'onPrimary',
  'statusBarItem.remoteHoverBackground': p => alpha(p.secondary, 0.25),
  'statusBarItem.remoteHoverForeground': 'secondary',
  'statusBarItem.warningBackground': () => alpha(CUSTOM.debugYellow, 0.25),
  'statusBarItem.warningForeground': () => CUSTOM.debugYellow,
  'statusBarItem.warningHoverBackground': () => alpha(CUSTOM.debugYellow, 0.38),
  'statusBarItem.warningHoverForeground': () => CUSTOM.debugYellow,

  // ── Title Bar ──
  'titleBar.activeBackground': 'surface',
  'titleBar.activeForeground': 'onSurface',
  'titleBar.border': 'surface',
  'titleBar.inactiveBackground': 'surface',
  'titleBar.inactiveForeground': 'onSurfaceVariant',

  // ── Menu ──
  'menu.background': 'surfaceContainer',
  'menu.foreground': 'onSurface',
  'menu.border': 'surfaceVariant',
  'menu.selectionBackground': 'surfaceVariant',
  'menu.selectionForeground': 'onPrimaryContainer',
  'menu.selectionBorder': 'primary',
  'menu.separatorBackground': 'surfaceVariant',

  // ── Command Center ──
  'commandCenter.background': 'surface',
  'commandCenter.foreground': 'onSurface',
  'commandCenter.activeForeground': 'onPrimaryContainer',
  'commandCenter.border': 'surfaceVariant',
  'commandCenter.activeBorder': 'primary',
  'commandCenter.inactiveForeground': 'onSurfaceVariant',
  'commandCenter.inactiveBorder': 'surfaceVariant',
  'commandCenter.activeBackground': 'surfaceVariant',
  'commandCenter.debuggingBackground': () => '#93000A',

  // ── Notification ──
  'notification.background': 'surfaceContainer',
  'notification.foreground': 'onSurface',
  'notification.border': 'surfaceVariant',
  'notificationCenter.border': 'surfaceVariant',
  'notificationCenterHeader.foreground': 'onPrimaryContainer',
  'notificationCenterHeader.background': 'surface',
  'notificationLink.foreground': 'secondary',
  'notificationsErrorIcon.foreground': 'error',
  'notificationsWarningIcon.foreground': () => CUSTOM.debugYellow,
  'notificationsInfoIcon.foreground': 'secondary',
  'notificationToast.border': 'surfaceVariant',
  'notifications.background': 'surfaceContainer',
  'notifications.border': 'surfaceVariant',
  'notifications.foreground': 'onSurface',

  // ── Banner ──
  'banner.background': 'surface',
  'banner.foreground': 'onSurface',
  'banner.iconForeground': 'primary',

  // ── Settings ──
  'settings.headerForeground': 'onPrimaryContainer',
  'settings.modifiedItemIndicator': 'primary',
  'settings.dropdownBackground': 'surfaceContainer',
  'settings.dropdownForeground': 'onSurface',
  'settings.dropdownBorder': 'surfaceVariant',
  'settings.dropdownListBorder': 'surfaceVariant',
  'settings.checkboxBackground': 'surfaceContainer',
  'settings.checkboxForeground': 'onSurface',
  'settings.checkboxBorder': 'surfaceVariant',
  'settings.textInputBackground': 'surfaceDim',
  'settings.textInputForeground': 'onSurface',
  'settings.textInputBorder': 'surfaceVariant',
  'settings.numberInputBackground': 'surfaceDim',
  'settings.numberInputForeground': 'onSurface',
  'settings.numberInputBorder': 'surfaceVariant',
  'settings.focusedRowBackground': p => alpha(p.primary, 0.12),
  'settings.focusedRowBorder': 'primary',
  'settings.headerBorder': 'surfaceVariant',
  'settings.rowHoverBackground': p => alpha(p.surfaceVariant, 0.3),
  'settings.sashBorder': 'surfaceVariant',
  'settings.settingsHeaderHoverForeground': 'primary',

  // ── Breadcrumb ──
  'breadcrumb.foreground': 'onSurfaceVariant',
  'breadcrumb.background': 'surface',
  'breadcrumb.focusForeground': 'onPrimaryContainer',
  'breadcrumb.activeSelectionForeground': 'onPrimaryContainer',
  'breadcrumbPicker.background': 'surfaceContainer',

  // ── Editor Snippet ──
  'editor.snippetTabstopHighlightBackground': p => alpha(p.primary, 0.25),
  'editor.snippetTabstopHighlightBorder': 'primary',
  'editor.snippetFinalTabstopHighlightBackground': () => alpha(CUSTOM.diffGreen, 0.25),
  'editor.snippetFinalTabstopHighlightBorder': () => CUSTOM.diffGreen,

  // ── Symbol Icons ──
  'symbolIcon.arrayForeground': 'primary',
  'symbolIcon.booleanForeground': () => CUSTOM.debugYellow,
  'symbolIcon.classForeground': 'onPrimaryContainer',
  'symbolIcon.colorForeground': () => CUSTOM.bracketCyan,
  'symbolIcon.constantForeground': 'primary',
  'symbolIcon.constructorForeground': 'secondary',
  'symbolIcon.enumeratorForeground': () => CUSTOM.debugYellow,
  'symbolIcon.enumeratorMemberForeground': () => CUSTOM.diffGreen,
  'symbolIcon.eventForeground': () => CUSTOM.bracketCyan,
  'symbolIcon.fieldForeground': 'secondary',
  'symbolIcon.fileForeground': 'onPrimaryContainer',
  'symbolIcon.folderForeground': 'onPrimaryContainer',
  'symbolIcon.functionForeground': 'secondary',
  'symbolIcon.interfaceForeground': 'onPrimaryContainer',
  'symbolIcon.keyForeground': 'primary',
  'symbolIcon.keywordForeground': 'primary',
  'symbolIcon.methodForeground': 'secondary',
  'symbolIcon.moduleForeground': 'primary',
  'symbolIcon.namespaceForeground': 'primary',
  'symbolIcon.nullForeground': () => CUSTOM.debugYellow,
  'symbolIcon.numberForeground': 'error',
  'symbolIcon.objectForeground': 'secondary',
  'symbolIcon.operatorForeground': 'primary',
  'symbolIcon.packageForeground': 'primary',
  'symbolIcon.propertyForeground': 'secondary',
  'symbolIcon.referenceForeground': 'secondary',
  'symbolIcon.snippetForeground': () => CUSTOM.bracketCyan,
  'symbolIcon.stringForeground': 'tertiary',
  'symbolIcon.structForeground': 'onPrimaryContainer',
  'symbolIcon.textForeground': 'onSurface',
  'symbolIcon.typeParameterForeground': 'onPrimaryContainer',
  'symbolIcon.unitForeground': () => CUSTOM.debugYellow,
  'symbolIcon.variableForeground': 'secondary',

  // ── Debug ──
  'debugToolBar.background': 'surfaceContainer',
  'debugToolBar.border': 'surfaceVariant',
  'debugConsole.infoForeground': 'secondary',
  'debugConsole.warningForeground': () => CUSTOM.debugYellow,
  'debugConsole.errorForeground': 'error',
  'debugConsole.sourceForeground': 'outline',
  'debugConsoleInputIcon.foreground': 'primary',
  'debugTokenExpression.name': 'secondary',
  'debugTokenExpression.value': () => CUSTOM.diffGreen,
  'debugTokenExpression.string': 'tertiary',
  'debugTokenExpression.boolean': 'error',
  'debugTokenExpression.number': 'error',
  'debugTokenExpression.error': 'error',
  'debugView.exceptionLabelForeground': 'error',
  'debugView.exceptionLabelBackground': p => alpha(p.error, 0.12),
  'debugView.stateLabelForeground': () => CUSTOM.diffGreen,
  'debugView.stateLabelBackground': () => alpha(CUSTOM.diffGreen, 0.12),
  'debugView.valueChangedHighlight': () => alpha(CUSTOM.debugYellow, 0.25),
  'debugTokenExpression.type': 'secondary',
  'debugExceptionWidget.background': 'surfaceContainer',
  'debugExceptionWidget.border': 'error',
  'editor.focusedStackFrameHighlightBackground': p => alpha(p.primary, 0.25),
  'editor.stackFrameHighlightBackground': p => alpha(p.primary, 0.12),
  'editor.inlineValuesBackground': p => alpha(p.secondary, 0.12),
  'editor.inlineValuesForeground': 'secondary',

  // ── Debug Icons ──
  'debugIcon.breakpointCurrentStackframeForeground': 'primary',
  'debugIcon.breakpointDisabledForeground': 'outline',
  'debugIcon.breakpointForeground': 'error',
  'debugIcon.breakpointStackframeForeground': 'secondary',
  'debugIcon.breakpointUnverifiedForeground': 'outline',
  'debugIcon.continueForeground': () => CUSTOM.diffGreen,
  'debugIcon.disconnectForeground': 'error',
  'debugIcon.pauseForeground': 'secondary',
  'debugIcon.restartForeground': 'primary',
  'debugIcon.startForeground': () => CUSTOM.diffGreen,
  'debugIcon.stepBackForeground': 'secondary',
  'debugIcon.stepIntoForeground': 'onSurface',
  'debugIcon.stepOutForeground': 'onSurface',
  'debugIcon.stepOverForeground': 'onSurface',
  'debugIcon.stopForeground': 'error',

  // ── Inline Chat ──
  'inlineChat.background': 'surfaceContainer',
  'inlineChat.foreground': 'onSurface',
  'inlineChat.border': 'surfaceVariant',
  'inlineChat.shadow': () => alpha(CUSTOM.black, 0.25),
  'inlineChatInput.border': 'surfaceVariant',
  'inlineChatInput.focusBorder': 'primary',
  'inlineChatInput.placeholderForeground': 'outline',
  'inlineChatInput.background': 'surfaceDim',
  'inlineChatDiff.inserted': () => alpha(CUSTOM.diffGreen, 0.25),
  'inlineChatDiff.insertedOutline': () => CUSTOM.diffGreen,
  'inlineChatDiff.removed': p => alpha(p.error, 0.25),
  'inlineChatDiff.removedOutline': 'error',

  // ── Inline Edit ──
  'inlineEdit.gutterIndicator.background': p => alpha(p.primaryContainer, 0.5),
  'inlineEdit.gutterIndicator.primaryBackground': 'primary',
  'inlineEdit.gutterIndicator.primaryBorder': 'primary',
  'inlineEdit.gutterIndicator.primaryForeground': 'onPrimary',
  'inlineEdit.gutterIndicator.secondaryBackground': 'secondary',
  'inlineEdit.gutterIndicator.secondaryBorder': 'secondary',
  'inlineEdit.gutterIndicator.secondaryForeground': () => CUSTOM.white,
  'inlineEdit.gutterIndicator.successfulBackground': () => CUSTOM.diffGreen,
  'inlineEdit.gutterIndicator.successfulBorder': () => CUSTOM.diffGreen,
  'inlineEdit.gutterIndicator.successfulForeground': () => CUSTOM.white,
  'inlineEdit.modifiedBackground': () => alpha(CUSTOM.diffGreen, 0.12),
  'inlineEdit.modifiedBorder': () => CUSTOM.diffGreen,
  'inlineEdit.modifiedChangedLineBackground': () => alpha(CUSTOM.diffGreen, 0.25),
  'inlineEdit.modifiedChangedTextBackground': () => alpha(CUSTOM.diffGreen, 0.38),
  'inlineEdit.originalBackground': p => alpha(p.error, 0.12),
  'inlineEdit.originalBorder': 'error',
  'inlineEdit.originalChangedLineBackground': p => alpha(p.error, 0.25),
  'inlineEdit.originalChangedTextBackground': p => alpha(p.error, 0.38),
  'inlineEdit.tabWillAcceptModifiedBorder': () => CUSTOM.diffGreen,
  'inlineEdit.tabWillAcceptOriginalBorder': 'error',

  // ── Terminal ──
  'terminal.background': 'surface',
  'terminal.foreground': 'onSurface',
  'terminal.ansiBlack': 'surface',
  'terminal.ansiRed': 'error',
  'terminal.ansiGreen': () => CUSTOM.diffGreen,
  'terminal.ansiYellow': () => CUSTOM.debugYellow,
  'terminal.ansiBlue': 'primary',
  'terminal.ansiMagenta': () => CUSTOM.debugPurple,
  'terminal.ansiCyan': () => CUSTOM.bracketCyan,
  'terminal.ansiWhite': 'onSurface',
  'terminal.ansiBrightBlack': 'onSurfaceVariant',
  'terminal.ansiBrightRed': 'error',
  'terminal.ansiBrightGreen': () => CUSTOM.diffGreen,
  'terminal.ansiBrightYellow': () => CUSTOM.debugYellow,
  'terminal.ansiBrightBlue': 'primary',
  'terminal.ansiBrightMagenta': () => CUSTOM.debugPurple,
  'terminal.ansiBrightCyan': () => CUSTOM.bracketCyan,
  'terminal.ansiBrightWhite': 'onPrimaryContainer',
  'terminal.selectionBackground': 'surfaceVariant',
  'terminal.inactiveSelectionBackground': p => alpha(p.surfaceVariant, 0.5),
  'terminalCursor.background': 'surface',
  'terminalCursor.foreground': 'onSurface',
  'terminal.findMatchBackground': p => alpha(p.primary, 0.38),
  'terminal.findMatchHighlightBackground': p => alpha(p.secondary, 0.25),
  'terminal.findMatchHighlightBorder': 'secondary',
  'terminal.tab.activeBorder': 'primary',
  'terminal.dropBackground': p => alpha(p.primary, 0.25),
  'terminal.border': 'surfaceVariant',
  'terminal.findMatchBorder': 'primary',
  'terminal.hoverHighlightBackground': p => alpha(p.primary, 0.12),
  'terminal.initialHintForeground': 'outline',
  'terminal.selectionForeground': 'onPrimaryContainer',
  'terminalCommandDecoration.defaultBackground': 'surfaceVariant',
  'terminalCommandDecoration.errorBackground': p => alpha(p.error, 0.25),
  'terminalCommandDecoration.successBackground': () => alpha(CUSTOM.diffGreen, 0.25),
  'terminalCommandGuide.foreground': 'outline',
  'terminalOverviewRuler.border': 'surfaceVariant',
  'terminalOverviewRuler.cursorForeground': p => alpha(p.primary, 0.5),
  'terminalOverviewRuler.findMatchForeground': p => alpha(p.primary, 0.5),
  'terminalStickyScroll.background': 'surfaceContainer',
  'terminalStickyScroll.border': 'surfaceVariant',
  'terminalStickyScrollHover.background': 'surfaceVariant',
  'terminalSymbolIcon.aliasForeground': 'primary',
  'terminalSymbolIcon.argumentForeground': 'secondary',
  'terminalSymbolIcon.branchForeground': 'primary',
  'terminalSymbolIcon.commitForeground': 'primary',
  'terminalSymbolIcon.fileForeground': 'onSurface',
  'terminalSymbolIcon.flagForeground': 'error',
  'terminalSymbolIcon.folderForeground': 'onSurfaceVariant',
  'terminalSymbolIcon.inlineSuggestionForeground': 'outline',
  'terminalSymbolIcon.methodForeground': 'secondary',
  'terminalSymbolIcon.optionForeground': 'onSurface',
  'terminalSymbolIcon.optionValueForeground': 'onSurface',
  'terminalSymbolIcon.pullRequestDoneForeground': () => CUSTOM.diffGreen,
  'terminalSymbolIcon.pullRequestForeground': 'primary',
  'terminalSymbolIcon.remoteForeground': 'secondary',
  'terminalSymbolIcon.stashForeground': 'onSurfaceVariant',
  'terminalSymbolIcon.symbolText': 'onSurface',
  'terminalSymbolIcon.symbolicLinkFileForeground': 'onSurface',
  'terminalSymbolIcon.symbolicLinkFolderForeground': 'onSurfaceVariant',
  'terminalSymbolIcon.tagForeground': 'primary',

  // ── Walkthrough / Welcome ──
  'walkThrough.embeddedEditorBackground': 'surfaceDim',
  'welcomePage.background': 'surface',
  'welcomePage.buttonBackground': 'surfaceVariant',
  'welcomePage.buttonHoverBackground': 'onSurfaceVariant',
  'welcomePage.tileBackground': 'surfaceContainer',
  'welcomePage.tileBorder': 'surfaceVariant',
  'welcomePage.tileHoverBackground': 'surfaceVariant',
  'walkthrough.stepTitle.foreground': 'onPrimaryContainer',
  'welcomePage.progress.background': 'surfaceVariant',
  'welcomePage.progress.foreground': 'primary',

  // ── Git Decorations ──
  'gitDecoration.addedResourceForeground': () => CUSTOM.diffGreen,
  'gitDecoration.modifiedResourceForeground': 'secondary',
  'gitDecoration.deletedResourceForeground': 'error',
  'gitDecoration.untrackedResourceForeground': 'primary',
  'gitDecoration.ignoredResourceForeground': 'outline',
  'gitDecoration.conflictingResourceForeground': () => CUSTOM.debugYellow,
  'git.blame.editorDecorationForeground': 'outline',
  'gitDecoration.renamedResourceForeground': 'secondary',
  'gitDecoration.stageDeletedResourceForeground': 'error',
  'gitDecoration.stageModifiedResourceForeground': 'secondary',
  'gitDecoration.submoduleResourceForeground': 'onSurfaceVariant',

  // ── SCM History ──
  'scm.historyGraph.commitHighlightForeground': 'primary',
  'scm.historyGraph.commitHighlightBorder': 'primary',
  'scm.historyGraph.historyItemChangesHighlightForeground': 'secondary',
  'scm.historyGraph.historyItemChangesHighlightBorder': 'secondary',

  // ── Extension ──
  'extensionButton.prominentForeground': () => CUSTOM.white,
  'extensionButton.prominentBackground': 'primary',
  'extensionButton.prominentHoverBackground': 'onPrimaryContainer',
  'extensionBadge.remoteBackground': 'secondary',
  'extensionBadge.remoteForeground': () => CUSTOM.white,
  'extensionButton.background': 'primary',
  'extensionButton.border': 'primary',
  'extensionButton.foreground': () => CUSTOM.white,
  'extensionButton.hoverBackground': 'onPrimaryContainer',
  'extensionButton.separator': 'surfaceVariant',
  'extensionIcon.preReleaseForeground': () => CUSTOM.debugYellow,
  'extensionIcon.privateForeground': () => CUSTOM.bracketCyan,
  'extensionIcon.sponsorForeground': () => CUSTOM.bracketPurple,
  'extensionIcon.starForeground': () => CUSTOM.debugYellow,
  'extensionIcon.verifiedForeground': 'primary',
  'mcpIcon.starForeground': () => CUSTOM.debugYellow,

  // ── Keybinding Label ──
  'keybindingLabel.background': 'surfaceVariant',
  'keybindingLabel.foreground': 'onSurface',
  'keybindingLabel.border': 'surfaceVariant',
  'keybindingLabel.bottomBorder': 'surfaceVariant',
  'keybindingTable.headerBackground': 'surfaceContainer',
  'keybindingTable.rowsBackground': 'surface',

  // ── Notebook ──
  'notebook.editorBackground': 'surface',
  'notebook.cellBorderColor': 'surfaceVariant',
  'notebook.cellHoverBackground': p => alpha(p.surfaceVariant, 0.5),
  'notebook.cellInsertionIndicator': 'primary',
  'notebook.cellEditorBackground': 'surfaceDim',
  'notebook.focusedCellBackground': 'surfaceContainer',
  'notebook.focusedCellBorder': 'primary',
  'notebook.inactiveFocusedCellBorder': 'surfaceVariant',
  'notebook.selectedCellBackground': 'surfaceVariant',
  'notebook.selectedCellBorder': 'primary',
  'notebook.cellStatusBarItemHoverBackground': 'surfaceVariant',
  'notebookOutput.background': 'surfaceDim',
  'notebookOutput.foreground': 'onSurface',
  'notebook.editorGutterBackground': 'surface',
  'notebookScrollbarSlider.background': p => alpha(p.onSurfaceVariant, 0.5),
  'notebookScrollbarSlider.hoverBackground': p => alpha(p.primary, 0.38),
  'notebookScrollbarSlider.activeBackground': p => alpha(p.primary, 0.5),
  'notebook.cellToolbarSeparator': 'surfaceVariant',
  'notebook.cellToolbarBackground': 'surfaceContainer',
  'notebook.cellToolbarBorder': 'surfaceVariant',
  'notebook.symbolHighlightBackground': p => alpha(p.primary, 0.12),
  'notebook.symbolHighlightBorder': p => alpha(p.primary, 0.25),
  'notebook.errorHighlightBackground': p => alpha(p.error, 0.12),
  'notebook.errorHighlightBorder': 'error',
  'notebook.warningHighlightBackground': () => alpha(CUSTOM.debugYellow, 0.12),
  'notebook.warningHighlightBorder': () => CUSTOM.debugYellow,
  'notebookChatEditHighlight': () => CUSTOM.bracketCyan,
  'notebook.focusedEditorBorder': 'primary',
  'notebook.inactiveSelectedCellBorder': 'surfaceVariant',
  'notebook.outputContainerBackgroundColor': 'surfaceDim',
  'notebook.outputContainerBorderColor': 'surfaceVariant',
  'notebookEditorOverviewRuler.runningCellForeground': () => CUSTOM.diffGreen,
  'notebookStatusErrorIcon.foreground': 'error',
  'notebookStatusRunningIcon.foreground': () => CUSTOM.bracketCyan,
  'notebookStatusSuccessIcon.foreground': () => CUSTOM.diffGreen,

  // ── Chart ──
  'chart.axis': 'outline',
  'chart.guide': 'surfaceVariant',
  'chart.line': 'onSurface',
  'charts.blue': 'secondary',
  'charts.foreground': 'onSurface',
  'charts.green': () => CUSTOM.diffGreen,
  'charts.lines': 'surfaceVariant',
  'charts.orange': () => CUSTOM.debugYellow,
  'charts.purple': () => CUSTOM.bracketPurple,
  'charts.red': 'error',
  'charts.yellow': () => CUSTOM.debugYellow,

  // ── Chat ──
  'chat.avatarBackground': 'primaryContainer',
  'chat.avatarForeground': 'onPrimaryContainer',
  'chat.checkpointSeparator': 'surfaceVariant',
  'chat.editedFileForeground': 'onPrimaryContainer',
  'chat.linesAddedForeground': () => CUSTOM.diffGreen,
  'chat.linesRemovedForeground': 'error',
  'chat.requestBackground': 'surfaceContainer',
  'chat.requestBorder': 'surfaceVariant',
  'chat.requestBubbleBackground': 'surfaceContainer',
  'chat.requestBubbleHoverBackground': 'surfaceVariant',
  'chat.requestCodeBorder': 'primary',
  'chat.slashCommandBackground': 'surfaceContainer',
  'chat.slashCommandForeground': 'primary',
  'chat.thinkingShimmer': p => alpha(p.primary, 0.12),
  'chatManagement.sashBorder': 'surfaceVariant',

  // ── Comments View ──
  'commentsView.resolvedIcon': 'outline',
  'commentsView.unresolvedIcon': 'primary',

  // ── Gauge ──
  'gauge.background': 'surfaceContainer',
  'gauge.border': 'surfaceVariant',
  'gauge.errorBackground': p => alpha(p.error, 0.25),
  'gauge.errorForeground': 'error',
  'gauge.foreground': 'onSurface',
  'gauge.warningBackground': () => alpha(CUSTOM.debugYellow, 0.25),
  'gauge.warningForeground': () => CUSTOM.debugYellow,

  // ── Interactive (Panel Chat) ──
  'interactive.activeCodeBorder': 'primary',
  'interactive.inactiveCodeBorder': 'surfaceVariant',

  // ── Markdown Alert ──
  'markdownAlert.caution.foreground': () => CUSTOM.debugYellow,
  'markdownAlert.important.foreground': () => CUSTOM.bracketPurple,
  'markdownAlert.note.foreground': 'secondary',
  'markdownAlert.tip.foreground': () => CUSTOM.diffGreen,
  'markdownAlert.warning.foreground': 'error',

  // ── Menu Bar ──
  'menubar.selectionBackground': 'surfaceVariant',
  'menubar.selectionBorder': 'primary',
  'menubar.selectionForeground': 'onPrimaryContainer',

  // ── Merge (classic) ──
  'merge.border': 'surfaceVariant',
  'merge.commonContentBackground': p => alpha(p.primary, 0.12),
  'merge.commonHeaderBackground': p => alpha(p.primary, 0.25),
  'merge.currentContentBackground': () => alpha(CUSTOM.diffGreen, 0.12),
  'merge.currentHeaderBackground': () => alpha(CUSTOM.diffGreen, 0.25),
  'merge.incomingContentBackground': p => alpha(p.secondary, 0.12),
  'merge.incomingHeaderBackground': p => alpha(p.secondary, 0.25),

  // ── Merge Editor ──
  'mergeEditor.change.background': p => alpha(p.primary, 0.12),
  'mergeEditor.change.word.background': p => alpha(p.primary, 0.25),
  'mergeEditor.changeBase.background': () => alpha(CUSTOM.bracketCyan, 0.12),
  'mergeEditor.changeBase.word.background': () => alpha(CUSTOM.bracketCyan, 0.25),
  'mergeEditor.conflict.handled.minimapOverViewRuler': p => alpha(p.primary, 0.5),
  'mergeEditor.conflict.handledFocused.border': 'primary',
  'mergeEditor.conflict.handledUnfocused.border': 'outline',
  'mergeEditor.conflict.input1.background': () => alpha(CUSTOM.diffGreen, 0.12),
  'mergeEditor.conflict.input2.background': p => alpha(p.secondary, 0.12),
  'mergeEditor.conflict.unhandled.minimapOverViewRuler': 'error',
  'mergeEditor.conflict.unhandledFocused.border': 'error',
  'mergeEditor.conflict.unhandledUnfocused.border': 'outline',
  'mergeEditor.conflictingLines.background': p => alpha(p.error, 0.12),

  // ── Ports ──
  'ports.iconRunningProcessForeground': 'primary',

  // ── Quick Picker ──
  'pickerGroup.border': 'surfaceVariant',
  'pickerGroup.foreground': 'onSurfaceVariant',
  'quickInput.background': 'surfaceContainer',
  'quickInput.foreground': 'onSurface',
  'quickInputList.focusBackground': 'surfaceVariant',
  'quickInputList.focusForeground': 'onPrimaryContainer',
  'quickInputList.focusIconForeground': 'onPrimaryContainer',
  'quickInputTitle.background': 'surface',

  // ── Simple Find Widget ──
  'simpleFindWidget.sashBorder': 'surfaceVariant',

  // ── Source Control Graph ──
  'scmGraph.foreground1': 'primary',
  'scmGraph.foreground2': () => CUSTOM.debugYellow,
  'scmGraph.foreground3': () => CUSTOM.diffGreen,
  'scmGraph.foreground4': 'secondary',
  'scmGraph.foreground5': 'error',
  'scmGraph.historyItemBaseRefColor': 'primary',
  'scmGraph.historyItemHoverAdditionsForeground': () => CUSTOM.diffGreen,
  'scmGraph.historyItemHoverDefaultLabelBackground': 'surfaceContainer',
  'scmGraph.historyItemHoverDefaultLabelForeground': 'onSurface',
  'scmGraph.historyItemHoverDeletionsForeground': 'error',
  'scmGraph.historyItemHoverLabelForeground': 'primary',
  'scmGraph.historyItemRefColor': 'primary',
  'scmGraph.historyItemRemoteRefColor': 'secondary',

  // ── Testing ──
  'testing.coverCountBadgeBackground': 'primary',
  'testing.coverCountBadgeForeground': 'onPrimary',
  'testing.coveredBackground': () => alpha(CUSTOM.diffGreen, 0.12),
  'testing.coveredBorder': () => CUSTOM.diffGreen,
  'testing.coveredGutterBackground': () => CUSTOM.diffGreen,
  'testing.iconErrored': 'error',
  'testing.iconErrored.retired': p => alpha(p.error, 0.5),
  'testing.iconFailed': 'error',
  'testing.iconFailed.retired': p => alpha(p.error, 0.5),
  'testing.iconPassed': () => CUSTOM.diffGreen,
  'testing.iconPassed.retired': () => alpha(CUSTOM.diffGreen, 0.5),
  'testing.iconQueued': () => CUSTOM.debugYellow,
  'testing.iconQueued.retired': () => alpha(CUSTOM.debugYellow, 0.5),
  'testing.iconSkipped': 'outline',
  'testing.iconSkipped.retired': 'outline',
  'testing.iconUnset': 'outline',
  'testing.iconUnset.retired': 'outline',
  'testing.message.error.badgeBackground': 'error',
  'testing.message.error.badgeBorder': 'error',
  'testing.message.error.badgeForeground': () => CUSTOM.white,
  'testing.message.error.lineBackground': p => alpha(p.error, 0.12),
  'testing.message.info.decorationForeground': 'secondary',
  'testing.message.info.lineBackground': p => alpha(p.secondary, 0.12),
  'testing.messagePeekBorder': 'primary',
  'testing.messagePeekHeaderBackground': 'surfaceContainer',
  'testing.peekBorder': 'primary',
  'testing.peekHeaderBackground': 'surfaceContainer',
  'testing.runAction': () => CUSTOM.diffGreen,
  'testing.uncoveredBackground': p => alpha(p.error, 0.12),
  'testing.uncoveredBorder': 'error',
  'testing.uncoveredBranchBackground': p => alpha(p.error, 0.25),
  'testing.uncoveredGutterBackground': 'error',
};

export function resolveColor(key, palette) {
  const rule = COLOR_MAP[key];
  if (!rule) {
    return null;
  }
  if (typeof rule === 'function') {
    return rule(palette);
  }
  if (Array.isArray(rule)) {
    const [role, alphaVal] = rule;
    return alpha(palette[role], alphaVal);
  }
  return palette[rule];
}
